name: ci-cd

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    uses: UNIANDES-202515-PROYECTO-II-G17-BACKEND/.github/.github/workflows/python-service.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
    secrets: inherit