name: ci-cd

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main, develop]

permissions:
  contents: write
  id-token: write

jobs:
  pipeline:
    uses: UNIANDES-202515-PROYECTO-II-G17-BACKEND/.github/.github/workflows/python-service.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
    secrets: inherit
